# Generated by Django 5.1.4 on 2025-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
