# Generated by Django 5.1.4 on 2025-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_website', '0002_userprofile_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile_info',
            name='password',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile_info',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
