# Generated by Django 5.1.4 on 2025-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_website', '0003_alter_conversation_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('specialization', models.CharField(max_length=50)),
                ('degrees', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('consultation_fee', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
